apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nischalrbhat/serv1:1.0
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb-service:27017/mydatabase
          ports:
            - containerPort: 3000
